### ISSUE TITLE
Different eventstore providers

### ISSUE THREAD

**Issue by kodeine** [AlexandreDecollas/CaviaJS#1]
Is there a possiblity to provide different eventstore providers? Like  mongodb, elastic search like in the package [node-eventstore](https://github.com/thenativeweb/node-eventstore)

**Comment by AlexandreDecollas** [comment]
Hi kodeine! how could I contact you? here is my email : alexandre.decollas.pro@gmail.com, feel free to ping me, I'd be glad to talk to you about this framework, as I know you currently work with nestjs-geteventstore, and as this project is aiming to replace it
